/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import com.revature.controllers.ReimbursementController;
import com.revature.controllers.UserController;
import com.revature.dao.IReimbursementDao;
import com.revature.dao.IUserDao;
import com.revature.dao.ReimbursementDao;
import com.revature.dao.UserDao;
import com.revature.services.ReimbursementServices;
import com.revature.services.UserServices;
import io.javalin.Javalin;
import static io.javalin.apibuilder.ApiBuilder.*;

public class App {

    public static void main(String args[]){
        IUserDao ud = new UserDao();
        UserServices us = new UserServices(ud);
        UserController uc = new UserController(us);

        IReimbursementDao rd = new ReimbursementDao();
        ReimbursementServices rs = new ReimbursementServices(rd);
        ReimbursementController rc = new ReimbursementController(rs);

        // javalin app
        Javalin server = Javalin.create(config -> {config.enableCorsForAllOrigins();});

        server.routes(()-> {
            path("users", () -> {
                get("/logout", uc.handleUserLogout);    // passed
                post("/register", uc.handleUserRegistration);   // passed
                post("/login", uc.handleUserLogin); // passed
                get("/{id}", uc.handleViewUser);   // available to employees (if userId is their own) and managers (route changed)
                get("/view/all", uc.handleViewUsers);    // passed (route changed)
                put("/update", uc.handleUpdateUser);    // passed
                delete("/delete/{id}", uc.handleDeleteUser);
            });
            path("reimbursement", () -> {
                post("/add", rc.handleAddReimbursement);    // passed

                put("/update", rc.handleUpdateReimbursement);   // passed
                delete("/delete/{id}", rc.handleDeleteReimbursement);
                get("/view/{id}", rc.handleViewReimbursementsOfAUser);  // passed
                get("/all", rc.handleViewReimbursements);   // passed (route changed)
            });
        });

        server.start(8000);
    }

}